# Generated by Django 5.0.7 on 2024-07-17 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('consulting_types', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consult.consultingtype')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultantAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_the_week', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3)),
                ('available_time', models.CharField(max_length=100)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consult.consultant')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consult.consultant')),
                ('consulting_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consult.consultingtype')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('time_slot', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('taken', 'Taken'), ('contacted', 'Contacted'), ('not-contacted', 'Not Contacted')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consult.consultant')),
                ('consulting_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consult.consultingtype')),
            ],
        ),
    ]
