# Generated by Django 5.0.7 on 2024-07-21 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultantAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_the_week', models.CharField(choices=[('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], max_length=3)),
                ('available_time', models.CharField(choices=[('1:00-3:00 Am', '1:00-3:00 Am'), ('3:00-5:00 Am', '3:00-5:00 Am'), ('5:00-7:00 Am', '5:00-7:00 Am'), ('7:00-9:00 Am', '7:00-9:00 Am'), ('9:00-11:00 Am', '9:00-11:00 Am'), ('12:00-1:00 pm', '12:00-1:00 pm'), ('1:00-3:00 pm', '1:00-3:00 pm')], max_length=100)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consult.consultant')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consult.consultant')),
                ('consulting_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consult.consultingtype')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('taken', 'Taken'), ('contacted', 'Contacted'), ('not-contacted', 'Not Contacted')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consult.consultant')),
                ('consultan_availability', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='consult.consultantavailability')),
                ('consulting_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consult.consultingtype')),
            ],
        ),
    ]
