# Generated by Django 5.0.7 on 2024-07-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_email_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('U', 'User'), ('FPM', 'Feeds Post Manager'), ('NPM', 'News Post Manager'), ('PM', 'Post Manager'), ('C', 'Consultant'), ('A', 'Admin'), ('SA', 'Super Admin')], default='U', max_length=30),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
